### ISSUE TITLE
请问支持远程连接吗？

### ISSUE THREAD

**Issue by zhsh2980** [codematrixer/hmdriver2#11]
hdc -s IP:8710 command 远程连接请问支持吗？
d = Driver("FMR0223C13000649")  括号中写远程的serial连接不上。

**Comment by codematrixer** [comment]
暂时不支持远程连接，USB数据线不能拔，因为需要进行端口映射，将手机上UITEST service的tcp端口映射到电脑端，这需要走usb的

**Comment by codematrixer** [comment]
但是支持另外一种远程连接，宿主机和设备之间的USB不能拔。然后通过如下「方式二」进行无线连接，再另一台电脑上就可以跑自动化了
<img width="966" alt="image" src="https://github.com/user-attachments/assets/7296b48c-a194-47cf-a9a0-008b274d58ca">

https://github.com/codematrixer/awesome-hdc?tab=readme-ov-file#%E6%97%A0%E7%BA%BF%E8%B0%83%E8%AF%95
