### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by gavinjhliu** [codematrixer/hmdriver2#12]
install接口对传入的hap文件路径默认加了单引号，运行时会报错
![image](https://github.com/user-attachments/assets/73d25d3e-910c-4f98-bdd3-38f7052a5793)
，去掉单引号可以正常运行

**Comment by gavinjhliu** [comment]
![image](https://github.com/user-attachments/assets/0bd02de7-d0c7-427a-afbe-89af92565a9a)

**Comment by codematrixer** [comment]
这个单引号是为了防止apkpath里有空格，比如包含空格或特殊字符：/Users/download/default-signed (5).hap
你是Windows是吧，我来适配下

**Comment by codematrixer** [comment]
- [ ]
