### ISSUE TITLE
有没有那种和安卓触控minitouch类似的操作指令，鼠标按下d、鼠标移动m、鼠标抬起u？

### ISSUE THREAD

**Issue by dwqdaiwenqi** [codematrixer/hmdriver2#16]
希望做到实时的拖动画面，而不是直接触发一个swipe指令

**Comment by codematrixer** [comment]
这个已支持 ， 参考README中 [复杂手势使用方法](https://github.com/codematrixer/hmdriver2?tab=readme-ov-file#%E5%A4%8D%E6%9D%82%E6%89%8B%E5%8A%BF)
复杂手势就是手指按下start，移动move，暂停pause的集合，最后运行action

**Comment by dwqdaiwenqi** [comment]
> 这个已支持，参考README中[复杂麦克风使用方法](https://github.com/codematrixer/hmdriver2?tab=readme-ov-file#%E5%A4%8D%E6%9D%82%E6%89%8B%E5%8A%BF) 复杂麦克风就是手指按启动，移动移动，暂停暂停的集合，最后运行动作

`d.gesture.start(x1, y1, interval=.5).move(x2, y2).pause(interval=1).move(x3, y3).action()`

**Comment by dwqdaiwenqi** [comment]
d.gesture.start(x1, y1, interval=.5).move(x2, y2).pause(interval=1).move(x3, y3).action()比如这个，只有在调用action的时候，才会整个手势触发吗？我想在调用move(x2, y2)过程中画面就会动，类似minitouch的触控，这个可以实现吗？

**Comment by codematrixer** [comment]
这个agent.so应该都有，我还没有实现，你可以去看看hypium的代码里找找

**Comment by dwqdaiwenqi** [comment]
代码里找到了，感谢
