### ISSUE TITLE
三个方法测试有点问题

### ISSUE THREAD

**Issue by bluepang2024** [codematrixer/hmdriver2#3]
d.set_display_rotation(DisplayRotation.ROTATION_90) - 不管用
d.screen_off() - 亮一下就黑了
d.unlock() - 点亮了，没有解锁成功，请求返回code401

**Comment by codematrixer** [comment]
> set_display_rotation

1. set_display_rotation  这个是需要app支持旋转才行，比如你进入到相册，打开一个图片，然后调下这个方法看看是否旋转了
2. d.screen_off() 这个就是关闭屏幕，d.screen_on() 才是点亮屏幕
3. d.unlock()  这个把完整log发一下呢

**Comment by codematrixer** [comment]
> d.unlock() - 点亮了，没有解锁成功，请求返回code401
fixed: https://github.com/codematrixer/hmdriver2/commit/527c0a15e75b80ec60ffff43299147d86a6608ed
