### ISSUE TITLE
请问下目前是不支持xpath选择器吗

### ISSUE THREAD

**Issue by alisleepy** [codematrixer/hmdriver2#7]
请问一下，目前不支持xpath选择器吗，使用时显示没有xpath属性

**Comment by codematrixer** [comment]
最新的版本支持了 v1.3.0
https://github.com/codematrixer/hmdriver2?tab=readme-ov-file#xpath%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by alisleepy** [comment]
恩恩，刚刚看到2小时前有提交，刚拉取了最新的，可以了，感谢

**Comment by codematrixer** [comment]
另外[ui-viewer](https://github.com/codematrixer/ui-viewer) 可以自动生成xpath lite，欢迎试用
